spring:
  datasource:
    url: jdbc:postgres://pg-dinner-plan-serious-notes.b.aivencloud.com:19398/dev?sslmode=require
    username: avnadmin
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    baseline-on-migrate: true
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 587
    username: 8a16e59bf57ec8
    password: ${SMTP_PASS_TEST}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
fe:
  host: http://localhost:8080
server:
  servlet:
    cookie:
      secure: true
      same-site: strict
