spring:
  datasource:
    url: jdbc:postgresql://pg-dinner-plan-serious-notes.b.aivencloud.com:19398/defaultdb?sslmode=require
    username: avnadmin
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    platform: postgresql
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  flyway:
    baseline-on-migrate: true
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 587
    username: 8a16e59bf57ec8
    password: ${SMTP_PASS_TEST}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
fe:
  host: ${FE_HOST}
server:
  servlet:
    cookie:
      secure: true
      same-site: strict
